<?php

/**
 * @file
 * DocBooks are Books that can be exported into DocBook/XML format.
 * It is also possible to import simple DocBook documents and
 * to convert Books to DocBooks.
 */

/**
 * Implements hook_help().
 */
function first_help($path, $arg) {
  if ($path == 'admin/help#first') {
    return t('A demonstration module.');
  }
}

/**
 * Implements hook_menu().
 */
/*
function docbook_menu() {
  $items['admin/content/docbook'] = array(
    'title' => 'DocBooks',
    'description' => "Manage your site's book outlines.",
    'page callback' => 'book_admin_overview',
    'access arguments' => array('administer book outlines'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'docbook.admin.inc',
  );
  return $items
}
*/

/**
 * Implements hook_element_info_alter().
 *
 * Sets the text format processor to a custom callback function.
 * This code is taken from: http://drupal.org/node/1003262#comment-4879140
 * See also this: http://drupal.stackexchange.com/questions/16036/set-a-default-text-format-per-content-type-in-drupal-7
 */
function docbook_element_info_alter(&$type) {
  if (isset($type['text_format']['#process'])) {
    foreach ($type['text_format']['#process'] as &$callback) {
      if ($callback === 'filter_process_format') {
        $callback = 'docbook_filter_process_format';
      }
    }
  }
}

/**
 * Callback for docbook_element_info_alter().
 */
function docbook_filter_process_format($element) {
  $element = filter_process_format($element);
  // Change the default text format of the field
  // 'field_dbw_content' to 'DocBookWiki'.
  if ($element['#bundle'] == 'docbook_section' && $element['#field_name'] == 'field_dbw_content') {
    $element['format']['format']['#default_value'] = 'docbookwiki';
  }
  return $element;
}
?>